[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:dotnet]
command=dotnet /app/RaveRadar.Api.dll
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:engine]
command=python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app/engine
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
